# Taken from https://github.com/mcullan/jupyter-actions/blob/master/.github/workflows/test_notebooks.yml

name: Test-Notebooks

# Run every time a new commit is pushed
on: push

jobs:
  # Set the job key
  test-notebooks:
    # Name the job
    name: Test Jupyter Notebooks
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: jupyter-actions
          environment-file: conda.yaml
          python-version: 3.9

      - name: Execute all Notebooks
        shell: bash -l {0}
        run: |
          conda activate jupyter-actions
          pytest
